
format:
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: resources/tex/preamble.tex
    citeproc: false # don't run pandoc default citation handling
    toc-depth: 1 # level 1 headings (i.e. parts and chapters)
    toc-title: Contents # title of table of contents
    # links-as-notes: true # turn URLs into sidenotes
    lot: true
    mainfont: ETbb # tufte font
    sansfont: Source Sans Pro
    citecolor: DarkGreen # tufte color
    linkcolor: DarkBlue # tufte color
    urlcolor: DarkGreen # tufte color
