project:
  type: book
  preview:
    port: 4200

resources:
  - CNAME
  
metadata-files:
  - _book.yml
  
# cap-location: margin       # figure and table captions in margin
reference-location: margin # footnotes in margin
link-citations: true       # citations link to references

bibliography: experimentology.bib
reference-section-title: References

df-print: kable
filters:
  - boxes
  - section-bibliographies

knitr:
  opts_chunk:
    comment: "#>"
    collapse: TRUE
    cache.lazy: FALSE
    dev: "png"
    dpi: 300

execute: 
  echo: false
  message: false
  warning: false
  error: false
  cache: true
  code-overflow: wrap
  tidy: true
