name: AutoBuild
on:
  push:
    branches: [ undergrad ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: poldrack/experimentology
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/experimentology
      options: --cpus 1
    steps:
      - name: render 
        run: make render-ug-html